FROM openjdk:8-jdk-alpine
EXPOSE 8080
VOLUME /tmp
RUN apk add --no-cache bash gawk sed grep bc coreutils
RUN apk add --no-cache mysql-client && rm -rf /var/lib/apt

ADD deployment/db-crud-app-0.0.1-SNAPSHOT.jar app.jar
ADD deployment/wait-for-it.sh wait-for-it.sh

ENTRYPOINT ["./wait-for-it.sh", "--timeout=15", "mysql-docker-container:3306", "--", "java","-jar","/app.jar"]