version: '3.1'

services:
    mysql-docker-container:
      image: mysql-image
      container_name: mysql-docker-container
      build:
        context: ./
        dockerfile: Dockerfile_mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_DATABASE: APPLICATION_DB
      volumes:
        - ./mysql-data/persistent:/var/lib/mysql
    ubuntu:
      image: ubuntu-image
      container_name: ubuntu-docker-container
      build:
        context: ./
        dockerfile: Dockerfile_ubuntu
      tty: true
    spring-boot-db-crud:
      image: spring-boot-db-crud-image
      container_name: spring-boot-db-crud-container
      build:
        context: ./
        dockerfile: Dockerfile_spring
      depends_on:
        - mysql-docker-container
      ports:
        - 8080:8080